In [1]:
import pandas as pd
import numpy as np
import ipywidgets as widgets
import mysql.connector

In [134]:
def get_credentials(usr, pswd, database, table, month, host = '132.248.182.174', port=3306):
    credentials = {
        'user': usr,
        'password': pswd,
        'host': host,
        'database': database,
        'port':port 
    }

    for k,v in credentials.items():
        print(k, v)

    # Convertimos la cadena de mes a número
    months = ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'dic']
    month = months.index(month) + 1
    print('Mes : ', month)
    # Obtenemos la cadena del año de la cadena de la base de datos
    db_year = database[-4:]

    print('file = ', database + '_' + months[month-1])
    
    try:
        conn = mysql.connector.connect(**credentials)
        
        if month != 1:
            query = "SELECT * FROM " + table + " where (month(timestamp)=" + str(month) + " or (month(timestamp)=" + str(month-1) + " and hour(timestamp)>17)" + ")" +" and year(timestamp)=" + db_year
        
        elif month == 1: # Tratamiento especial para el mes de enero
            db_pass_year = str(int(db_year) - 1)
            query = "select * from " + table + " where (month(timestamp)=12 and year(timestamp)="  + db_pass_year + " and day(timestamp)=31 and hour(timestamp)>17) or (month(timestamp)=1 and year(timestamp)=" +  db_year + ")"        

        print('Query : ', query)
        data = pd.read_sql(query, conn)
        data.to_csv(database + '_' + months[month-1])

        print(data)
        
        conn.close()
        
    except mysql.connector.Error as err:
        print('Error de conexión a la base de datos:', err)

In [135]:
w_user = widgets.Text(
    value='',
    placeholder='Type something',
    description='Usuario',
    layout=widgets.Layout(width='190px'),
    disabled=False   
)

w_pswd = widgets.Text(
    value='',
    placeholder='Type something',
    description='Clave',
    layout=widgets.Layout(width='190px'),
    disabled=False   
)

w_db = widgets.Text(
    value='BSRN_2023', # Valor por omisión
    description='BD',
    layout=widgets.Layout(width='190px'),
    disabled=False   
)

w_table = widgets.Text(
    value='bsrn_2023_null', # Valor por omisión
    description='Tabla',
    layout=widgets.Layout(width='190px'),
    disabled=False   
)

w_month = widgets.Dropdown(
    options=['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'dic'], 
    description='Mes',
    layout=widgets.Layout(width='190px'),
    disabled=False   
)

w_button = widgets.Button(
    description="", icon='play',
    layout=widgets.Layout(width='50px')    
)

ui = widgets.VBox([w_user, w_pswd, w_db, w_table, w_month, w_button])
ui.layout = widgets.Layout(border='solid 1px black')
ui.layout.width = '200px'

output = widgets.Output()

display(ui, output)

def on_button_clicked(b):
    output.clear_output(wait=True)
    with output:
        get_credentials(usr = w_user.value, 
                        pswd = w_pswd.value, 
                        database = w_db.value,
                        table = w_table.value,
                        month = w_month.value)

w_button.on_click(on_button_clicked)

VBox(children=(Text(value='', description='Usuario', layout=Layout(width='190px'), placeholder='Type something…

Output()

,TIMESTAMP,RECORD,ZenDeg,AzDeg,AirMass,CRBattVolt_Avg,CRPTemp_Avg,ProcessTime_s_Max,GLOBAL_Avg,GLOBAL_Std,...,DWSIGNAL_Avg,UWSIGNAL_Avg,DWIRTEMPC_Avg,DWTERMO_Avg,UWIRTEMPC_Avg,UWTERMO_Avg,UVBw_Avg,UVBw_Std,UVBw_Min,UVBw_Max
0,2023-05-01 18:00:00,66774,84.5842,284.368,8.29,12.53,42.46,1.058,44.23260,1.339,...,-593.795,-480.1130,35.32,-86.40,36.08,-32.550,0.001237,0.0,0.001186,0.001301
1,2023-05-01 18:01:00,66775,84.8122,284.431,8.60,12.53,42.47,1.057,39.97260,1.117,...,-584.076,-479.5480,35.28,-85.00,36.03,-32.510,0.001149,0.0,0.001090,0.001225
2,2023-05-01 18:02:00,66776,85.0401,284.493,8.92,12.53,42.47,1.057,36.24450,1.102,...,-584.343,-460.3090,35.23,-85.10,35.99,-31.210,0.001068,0.0,0.001014,0.001129
3,2023-05-01 18:03:00,66777,85.2674,284.558,9.27,12.52,42.48,1.057,31.90810,1.447,...,-584.122,-447.1290,35.14,-85.00,35.94,-30.310,0.000991,0.0,0.000937,0.001052
4,2023-05-01 18:04:00,66778,85.4937,284.621,9.64,12.52,42.48,1.057,26.75880,1.412,...,-587.662,-438.0860,35.02,-85.50,35.87,-29.700,0.000934,0.0,0.000880,0.000995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54355,2023-06-30 23:55:00,153529,140.8780,353.888,0.00,12.36,29.53,1.106,-1.30457,0.010,...,-264.791,70.5689,22.29,-38.54,23.57,4.784,0.000027,0.0,0.000019,0.000039
54356,2023-06-30 23:56:00,153530,140.9030,354.251,0.00,12.36,29.52,1.121,-1.30114,0.009,...,-261.197,72.5102,22.29,-38.02,23.58,4.916,0.000031,0.0,0.000019,0.000058
54357,2023-06-30 23:57:00,153531,140.9260,354.613,0.00,12.36,29.50,1.121,-1.31370,0.019,...,-258.068,70.6352,22.30,-37.56,23.59,4.789,0.000027,0.0,0.000000,0.000058
54358,2023-06-30 23:58:00,153532,140.9490,354.976,0.00,12.36,29.49,1.106,-1.30457,0.010,...,-254.784,68.9489,22.30,-37.09,23.61,4.675,0.000028,0.0,0.000019,0.000077
54359,2023-06-30 23:59:00,153533,140.9690,355.340,0.00,12.36,29.48,1.106,-1.35250,0.026,...,-253.807,67.5288,22.31,-36.94,23.62,4.578,0.000028,0.0,0.000019,0.000058

In [242]:
def data_processing(df, database, month):

    # Leemos el archivo correspondiente
    months = ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'dic']
    filename = database + '_' + months[month-1]
    df = pd.read_csv(filename, index_col=0)
    
    # Conversion de columna 'TIMESTAMP' al formato de fecha de pandas (datatime64)
    # Esto permite acceder a algunos parámetros de esta columna, como .dt.month 
    df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'], format='%Y-%m-%d %H:%M:%S')

    #df["TIMESTAMP"]=df["TIMESTAMP"] + pd.Timedelta(hours=6)

    # Eliminamos los renglones que no sean del mes que se está analizando
    df=df[df["TIMESTAMP"].dt.month == month]

    # Determinamos la fecha inicial y la fecha final
    start_date = df['TIMESTAMP'].iloc[0]
    end_date = df['TIMESTAMP'].iloc[-1]

#    print(start_date, end_date)

    # Conversion de la temperatura a Grados Kelvin
    to_kelvin = lambda t: t + 273.15
    df['CRPTemp_Avg']=to_kelvin(df['CRPTemp_Avg'])
    df['UVTEMP_Avg']=to_kelvin(df['UVTEMP_Avg'])
    df["DEW_POINT_Avg"] = to_kelvin(df["DEW_POINT_Avg"])

    # Agregamos la columna: GH_CALC_Avg - GLOBAL_Avg
    df["dif_GH_CALC_GLOBAL"] = df["GH_CALC_Avg"] - df["GLOBAL_Avg"]

    # Agregamos la columna: porcentaje de la diferencia
    df["percent_dif_GH_CALC_GLOBAL"] = 100 * abs(df["dif_GH_CALC_GLOBAL"]) / df["GH_CALC_Avg"]

    # Agregamos la columna: "dispersion" con los datos de df["GH_CALC_Avg"]
    df["dispersion"] = df["GH_CALC_Avg"]

    # Agregamos la columna datos de dispersion al 1%.
    df["percent_dispersion"] = 0.01 * df["dispersion"]

    # Agregamos una columna vacía
    df["empty"]=""

    # Agregamos una columna con valores enteros -999
    df["null_int"]=-999

    # Agregamos una columna con valores flotantes -99.9
    df["null_float1"]=-99.9

    # Agregamis una columna con valores flotantes -99.99
    df["null_float2"]=-99.99

    # Lista con todas las columnas del DataFrame
    columns = list(df.columns)

#    print(columns)

### <-------- NO VEO DONDE SE USAN ESTAS LISTAS -------->    
    # Listas con nombres de columnas sin su terminación (_Avg, _Std, _Min, _Mix)
    avg_list = [x.replace("_Avg","") for x in columns if x.endswith("Avg")]
    std_list = [x.replace("_Std","") for x in columns if x.endswith("Std")]
    min_list = [x.replace("_Min","") for x in columns if x.endswith("Min")]
    max_list = [x.replace("_Max","") for x in columns if x.endswith("Max")]
    
    # Determinamos los nombres comunes en las listas anteriores y los juntamos
    # en una lista
    common_list = list(set(avg_list) & set(std_list) & set(min_list) & set(max_list))

    # A esos nombres comunes les agregamos las terminaciones y los guardamos en una lista.
    aux = [elemento + "_" + str(i) for elemento in common_list for i in ["Avg","Std","Min","Max"]]

    # Eliminamos los nombres comunes de las columnas:
    unique_columns=columns.copy()    
    for i in aux:
        unique_columns.remove(i)

    unique_columns.remove("TIMESTAMP")
    unique_columns.remove("RECORD")
### <-------- --------------------------------- -------->    
    
    # Columnas del DataFrame organizadas por categoría.
    basic_parameters  = ["GLOBAL", "DIRECT", "DIFFUSE", "GH_CALC_Avg"]
    shortwave_balance = ["GLOBAL", "UPWARD_SW"]
    longwave_balance  = ["DOWNWARD", "UPWARD_LW", "DWIRTEMP", "UWIRTEMP", "CRPTemp_Avg"]
    meteorology       = ["CRPTemp_Avg", "RELATIVE_HUMIDITY_Avg", "PRESSURE_Avg", "DEW_POINT_Avg"]
    ultraviolet       = ["UVB", "UVTEMP_Avg", "UVSIGNAL_Avg"]
    statistics        = ["dif_GH_CALC_GLOBAL", "percent_dif_GH_CALC_GLOBAL", "dispersion"]

    categories = [basic_parameters, 
                  shortwave_balance, 
                  longwave_balance, 
                  meteorology, 
                  ultraviolet,
                  statistics]

    # others es un sinónimo de columns, cualquier acción sobre others afecta también a columns
#    others = columns 
#    for j in list(df.columns[-8:]):
#       others.remove(j)
#    categories.append(others)
    
    # El código anterior puede sustituirse por la siguiente línea:
    categories.append(columns[0:-8])
#    print(categories)

    names_categories=["Parámetros Básicos",
                      "Balance de onda corta",
                      "Balance de onda larga",
                      "Meteorología",
                      "Ultravioleta",
                      "Dispersión",
                      "Otros"]
    
    climatic_categories = dict(zip(names_categories, categories))

#    for k, v in climatic_categories.items():
#        print(k, v)
    
    return df

In [243]:
data_processing(df, 'BSRN_2023', 4)

,TIMESTAMP,RECORD,ZenDeg,AzDeg,AirMass,CRBattVolt_Avg,CRPTemp_Avg,ProcessTime_s_Max,GLOBAL_Avg,GLOBAL_Std,...,UVBw_Min,UVBw_Max,dif_GH_CALC_GLOBAL,percent_dif_GH_CALC_GLOBAL,dispersion,percent_dispersion,empty,null_int,null_float1,null_float2
11160,2023-04-01 00:00:00,22494,159.544,351.426,0.0,12.44,302.84,1.111,-4.10801,0.011,...,0.000019,0.000058,-0.74625,-15.373095,-4.85426,-0.048543,,-999,-99.9,-99.99
11161,2023-04-01 00:01:00,22495,159.579,352.132,0.0,12.44,302.82,1.109,-4.09432,0.021,...,0.000019,0.000058,-0.74134,-15.330689,-4.83566,-0.048357,,-999,-99.9,-99.99
11162,2023-04-01 00:02:00,22496,159.610,352.841,0.0,12.44,302.80,1.095,-4.06467,0.018,...,0.000019,0.000058,-0.76569,-15.851614,-4.83036,-0.048304,,-999,-99.9,-99.99
11163,2023-04-01 00:03:00,22497,159.637,353.553,0.0,12.44,302.79,1.094,-4.07152,0.026,...,0.000019,0.000058,-0.74821,-15.523899,-4.81973,-0.048197,,-999,-99.9,-99.99
11164,2023-04-01 00:04:00,22498,159.663,354.266,0.0,12.43,302.77,1.108,-4.08750,0.017,...,0.000019,0.000058,-0.72558,-15.075170,-4.81308,-0.048131,,-999,-99.9,-99.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54355,2023-04-30 23:55:00,65689,149.104,355.233,0.0,12.37,305.23,1.104,-1.54314,0.033,...,0.000019,0.000038,-0.23139,-13.039509,-1.77453,-0.017745,,-999,-99.9,-99.99
54356,2023-04-30 23:56:00,65690,149.123,355.702,0.0,12.37,305.21,1.104,-1.64244,0.055,...,0.000019,0.000039,-0.32232,-16.405057,-1.96476,-0.019648,,-999,-99.9,-99.99
54357,2023-04-30 23:57:00,65691,149.140,356.171,0.0,12.37,305.19,1.104,-1.80794,0.053,...,0.000019,0.000058,-0.96427,-34.783440,-2.77221,-0.027722,,-999,-99.9,-99.99
54358,2023-04-30 23:58:00,65692,149.154,356.640,0.0,12.37,305.18,1.104,-1.89012,0.019,...,0.000019,0.000038,-1.30244,-40.796101,-3.19256,-0.031926,,-999,-99.9,-99.99
54359,2023-04-30 23:59:00,65693,149.167,357.111,0.0,12.37,305.16,1.104,-1.93920,0.019,...,0.000019,0.000058,-0.97135,-33.373417,-2.91055,-0.029106,,-999,-99.9,-99.99